In [1]:
# QUESTION - 1
import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [45]:
#QUESTION 2
import numpy as np
a1 = []
for i in range(0,5,1):
    b = int(input(""))
    a1.append(b)
array1 = np.asarray(a1)
print(array1)
a2 = []
for j in range(0,5,1):
    c = int(input(""))
    a2.append(c)
array2 = np.asarray(a2)
print(array2)
array = np.concatenate((array1,array2),axis=0)
print(array)
print(np.sort(array))

    

    

 1
 2
 3
 4
 5


[1 2 3 4 5]


 6
 7
 8
 9
 0


[6 7 8 9 0]
[1 2 3 4 5 6 7 8 9 0]
[0 1 2 3 4 5 6 7 8 9]


In [46]:
# QUESTION - 3
import numpy as np
a = [[7,8],[9,4],[5,6],[1,2],[3,2]] # sample array
b= np.array(a)
print("dimensions:",b.shape) # prints the dimesion if the array in the (no of rows, no of columns)
print("size:",b.size) # prints the no of elements(size) of the array 


dimensions: (5, 2)
size: 10


In [1]:
# QUESTION - 4
import numpy as np
a = [1,2,3,4]
b = np.array(a)
print("dimension",b.shape)
b1 = b[np.newaxis,:] # using np.newais to create a row wise 2D array
print("dimesnsion",b1.shape)
print(b1)
b2 = b[:,np.newaxis] # using np.newaxis to create a column wise 2D array
print("dimension",b2.shape)
print(b2)
b3 = np.expand_dims(b,axis = 0) #using np.expand_dims to create a 2D array along 0th axis
print("dimesnsion",b3.shape)
print(b3)
b4 = np.expand_dims(b,axis = 1) # using np.expand_dims to create a 2D array along 1st axis
print("dimension",b4.shape)
print(b4)

dimension (4,)
dimesnsion (1, 4)
[[1 2 3 4]]
dimension (4, 1)
[[1]
 [2]
 [3]
 [4]]
dimesnsion (1, 4)
[[1 2 3 4]]
dimension (4, 1)
[[1]
 [2]
 [3]
 [4]]


In [32]:
# QUESTION - 5
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[4,5,6],[1,2,3]])
vs = np.vstack((a,b)) #stacks array in the vertical order 
hs = np.hstack((a,b)) #stacks array in the hosrizontal order
print(vs)
print()
print(hs)


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]

[[1 2 3 7 8 9]
 [4 5 6 4 5 6]
 [7 8 9 1 2 3]]


In [44]:
# QUESTION - 6
import numpy as np
a = np.array([1,2,2,3,3,4,5,5,6,7,8,8,9])
print(np.unique(a)) # generates only the unique valus from the given array
print(np.unique(a,return_counts=True)) #generates the count of the uniqu numbers

[1 2 3 4 5 6 7 8 9]
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 2, 1, 2, 1, 1, 2, 1]))
